### PR TITLE
fix!: `TransactionResponse` class

### LINKED ISSUE #91: Add support for `TransactionResponse.Preconditions`

### LINKED ISSUE #92: Fix `TransactionResponse` class
- Add missing properties: `id`, `fee_meta_xdr`, `preconditions`
- Add missing property for `_links.transaction`
- Remove deprecated `result_meta_xdr` property
- Fix transaction JSON test files: update properties and correct data types

### PR DESCRIPTION
**Pull request by cuongph87**
## Types of changes
- Fixes #91
- Fixes #92 
- Adds `required` modifier to always-present properties

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

---

> [!NOTE]
> Refactors `TransactionResponse` (breaking) to match Horizon: adds required fields, changes several types/fields, introduces preconditions/links, and updates tests/fixtures accordingly.
> 
> - **Responses**:
>   - **`TransactionResponse`**:
>     - Make class `sealed`; add required fields (`id`, `links`, etc.).
>     - Change types: `created_at` to ISO string; `fee_charged`/`max_fee` to string; muxed IDs to string.
>     - Add `fee_meta_xdr`, `preconditions`; remove `result_meta_xdr`.
>     - Update nested types: `InnerTransaction.max_fee` to string; stricter memo handling (invalid ops throw `InvalidOperationException`).
>   - **Links/Preconditions**:
>     - Extract `TransactionResponseLinks` (adds `transaction` link; `precedes`/`succeeds` now pages).
>     - Add `TransactionResponsePreconditions` with `TimeBounds` and optional bounds/signers.
> - **Tests & Data**:
>   - Replace legacy transaction fixtures with `transaction.json`; add `transactionWithTextMemo.json`; update muxed/fee-bump fixtures (string fees, new links).
>   - Update assertions to new types/fields (e.g., `CreatedAt` string, `FeeMetaXdr`, memo handling).
>   - Adjust streaming and payment operation tests to new transaction shape.
>   - Update test project includes to new/renamed files.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0a8ab057b0391cbe2871fbf896c2b7e0a530a01c. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: StellarDotnetSdk/Responses/TransactionResponse.cs [hunk 1]
```diff
@@ -2,87 +2,181 @@
...
 
+    /// <summary>
+    ///     The muxed account ID of the fee account, if applicable.
+    /// </summary>
     [JsonPropertyName("fee_account_muxed_id")]
-    public ulong? FeeAccountMuxedId { get; set; }
-
-    [JsonPropertyName("memo")] public string? MemoValue { get; init; }
-
+    public string? FeeAccountMuxedId { get; init; }
```
Comment (jopmiddelkamp) [inline StellarDotnetSdk/Responses/TransactionResponse.cs]: And this? Well I'm not adding anything else anymore if Copilot already marked them.

[the remark this answers is not in the document]
Comment (cuongph87) [reply StellarDotnetSdk/Responses/TransactionResponse.cs]: Duplicate.

File: StellarDotnetSdk/Responses/TransactionResponse.cs [hunk 2]
```diff
@@ -2,87 +2,181 @@
...
     [JsonPropertyName("ledger")]
-    public long Ledger { get; init; }
+    public required long Ledger { get; init; }
 
+    /// <summary>
+    /// An ISO 8601 formatted string of when the transaction was created.
+    /// </summary>
     [JsonPropertyName("created_at")]
-    public DateTime CreatedAt { get; init; }
+    public required string CreatedAt { get; init; }
```
Comment (jopmiddelkamp) [inline StellarDotnetSdk/Responses/TransactionResponse.cs]: Should this not be a `DateTime`?
```suggestion
    public required DateTime CreatedAt { get; init; }
```

File: StellarDotnetSdk/Responses/TransactionResponsePreconditions.cs [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    ///     The lower bound.
+    /// </summary>
+    [JsonPropertyName("min_ledger")]
+    public string? MinLedger { get; init; }
+
+    /// <summary>
+    ///     The upper bound.
+    /// </summary>
+    [JsonPropertyName("max_ledger")]
+    public string? MaxLedger { get; init; }
```
Comment (jopmiddelkamp) [inline StellarDotnetSdk/Responses/TransactionResponsePreconditions.cs]: Should we not have more specific types here?
```suggestion
    /// <summary>
    ///     The lower bound.
    /// </summary>
    [JsonPropertyName("min_ledger")]
    public uint? MinLedger { get; init; }

    /// <summary>
    ///     The upper bound.
    /// </summary>
    [JsonPropertyName("max_ledger")]
    public uint? MaxLedger { get; init; }
```

File: StellarDotnetSdk/Responses/TransactionResponse.cs (hunk 2 above)
Comment (cuongph87) [reply StellarDotnetSdk/Responses/TransactionResponse.cs]: It should either `DateTimeOffset` or `string`. `DateTime` omits the timezone part. I'm thinking about creating a separate follow-up PR to fix all these DateTime occurrences. Do you agree?

File: StellarDotnetSdk/Responses/TransactionResponsePreconditions.cs [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+    ///     The lower bound.
+    /// </summary>
+    [JsonPropertyName("min_time")]
+    public required string MinTime { get; init; }
+
+    /// <summary>
+    ///     The upper bound.
+    /// </summary>
+    [JsonPropertyName("max_time")]
+    public string? MaxTime { get; init; }
```
[the remark this answers is not in the document]
Comment (cuongph87) [reply StellarDotnetSdk/Responses/TransactionResponsePreconditions.cs]: The official docs state that "The time range for which this transaction is valid, with bounds as unsigned 64-bit UNIX timestamps". So, I think `long` is enough.
If we add the convenient `MinTimeUnix` property here, we will also need to add it for similar places, which I think unnecessary.

[the remark this answers is not in the document]
Comment (jopmiddelkamp) [reply StellarDotnetSdk/Responses/TransactionResponsePreconditions.cs]: Fine too just wanted to make it a bit more easy for our users. Won't hurt I think
